{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-scheduler
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - |
              curl -X GET "http://{{ .Release.Name }}-service:{{ .Values.service.port }}/scan/costs" || true
              curl -X GET "http://{{ .Release.Name }}-service:{{ .Values.service.port }}/scan/security" || true
              curl -X GET "http://{{ .Release.Name }}-service:{{ .Values.service.port }}/scan/hygiene" || true
              curl -X GET "http://{{ .Release.Name }}-service:{{ .Values.service.port }}/scan/network" || true
          restartPolicy: OnFailure
{{- end}}