apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "opsguardian.name" . }}
        app.kubernetes.io/name: {{ include "opsguardian.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: opsguardian
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.env.targetPort }}
        env:
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.awsRegion }}
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "opsguardian.fullname" . }}-secret
              key: SLACK_WEBHOOK_URL
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "opsguardian.fullname" . }}-secret
              key: SLACK_BOT_TOKEN
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "opsguardian.fullname" . }}-secret
              key: SLACK_APP_TOKEN
        - name: SLACK_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "opsguardian.fullname" . }}-secret
              key: SLACK_CHANNEL_ID