apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "opsguardian.fullname" . }}-secret
  labels:
    {{- include "opsguardian.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: {{ include "opsguardian.fullname" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: opsguardian/slack-webhook-url
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: opsguardian/slack-bot-token
    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: opsguardian/slack-app-token
    - secretKey: SLACK_CHANNEL_ID
      remoteRef:
        key: opsguardian/slack-channel-id
