apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsguardian.fullname" . }}-secret
  labels:
    {{- include "opsguardian.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_DEFAULT_REGION: {{ "us-east-1" | b64enc | quote}}
  SLACK_WEBHOOK_URL: {{ .Values.slack.webhookUrl | b64enc | quote}}