image:
  repository: 279987127424.dkr.ecr.us-east-1.amazonaws.com/opsguardian
  tag: "48b097a9"
  pullPolicy: Always

awsRegion: "us-east-1"

replicaCount: 1

service:
  type: ClusterIP
  port: 80

cronjob:
  enabled: true
  schedule: "*/2 * * * *"

env:
  targetPort: 8000

podSecurityContext: {}

serviceAccount:
  create: true
  name: "opsguardian-sa"
  roleArn: ""
  annotations: {}
