image:
  repository: omerbh7/opsguardian
  tag: "v14"
  pullPolicy: Always

slack:
  webhookUrl: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 80

cronjob:
  enabled: true
  schedule: "*/2 * * * *"
  dryRun: true

aws:
  accessKey: ""
  secretKey: ""

slack:
  webhookUrl: ""

env:
  targetPort: 8000

serviceAccount:
  create: true
  name: "opsguardian-sa"
  annotations: {}
