image:
  repository: 279987127424.dkr.ecr.us-east-1.amazonaws.com/opsguardian
  tag: "ba542927"
  pullPolicy: Always

slack:
  webhookUrl: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 80

cronjob:
  enabled: true
  schedule: "*/2 * * * *"
  dryRun: true

env:
  targetPort: 8000

serviceAccount:
  create: true
  name: "opsguardian-sa"
  roleArn: ""
  annotations: {}
