image:
  repository: opsguardian
  tag: "v2"
  pullPolicy: Never

slack:
  webhookUrl: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 80

cronjob:
  enabled: true
  schedule: "*/2 * * * *"
  dryRun: true

aws:
  accessKey: ""
  secretKey: ""

slack:
  webhookUrl: ""

env:
  targetPort: 8000